name: fodome
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  location: ^4.3.0
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  image_picker: ^0.8.0+3
  firebase_storage: ^8.1.3
  firebase_auth: ^1.4.1
  google_sign_in: ^5.0.4
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  uuid: ^3.0.4
  image: ^3.0.2
  animator: ^3.0.0
  path_provider: ^2.0.2
  firebase_messaging: ^10.0.2
  timeago: ^3.1.0
  cached_network_image: ^3.0.0
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.6
  settings_ui: ^1.0.0
  permission_handler: ^8.1.1
  android_intent: ^2.0.2
  google_maps_flutter: ^2.0.6
  overlay_support: ^1.2.1
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Spotify
      fonts:
        - asset: assets/fonts/Spotify/medium.ttf
        - asset: assets/fonts/Spotify/bold.otf
          weight: 700
  assets:
    - assets/images/
    
